apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
      - name: test1-ubuntu
        image: dahuajuan/ubuntu-with-test1
        command: ["/bin/bash","-c","--"]
        args: ["while true; do sleep 30; done;"]
        resources:
          requests:
            memory: "500Mi"
          limits:
            memory: "600Mi"
