apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache1
spec:
  selector:
    matchLabels:
      run: php-apache1
  replicas: 1
  template:
    metadata:
      labels:
        run: php-apache1
    spec:
      containers:
      - name: php-apache1
        image: dahuajuan/php-ram-test
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m

---

apiVersion: v1
kind: Service
metadata:
  name: php-apache1
  labels:
    run: php-apache1
spec:
  ports:
  - port: 80
  selector:
    run: php-apache1

