apiVersion: v1
kind: Pod
metadata:
  name: test1
spec:
  containers:
  - name: dahuajuan/ubuntu-with-test1
    command: ["/bin/bash","-c","--"]
    args: ["while true; do sleep 30; done;"]
    image: ubuntu
    resources:
      requests:
        memory: "500Mi"
      limits:
        memory: "600Mi"
